vim.wo.number = true -- make line numbers default (default: false)
vim.o.clipboard = 'unnamedplus' -- sync clipboard between OS and Neovim (default: '')
vim.o.linebreak = true -- companion to wrap, don't split words (default: false)
vim.o.autoindent = true -- copy indent from current line when starting new one (default: true)
vim.o.ignorecase = true -- case-insensitive searching UNLESS \C or capital in search (default: false)
vim.o.smartcase = true -- used with ignorecase. If searching with all lowercase, case-insensitive, but if including an upper case, case-sensitive
vim.o.shiftwidth = 4 -- how many spaces to indent/unindent with commands like >>, <<, ==, or auto-indent when writing new lines
vim.o.tabstop = 4 -- the number of spaces a real tab character(\t) looks like (default: 8)
vim.o.softtabstop = 4 -- how many spaces pressing <Tab> or <BS> counts as in insert mode. with expandtab=true: pressing <Tab> inserts that many spaces. with expandtab=false: pressing <Tab> may still insert a real \t, but <BS> will treat groups of softtabstop spaces as one unit to delete
vim.o.expandtab = true -- convert tabs to spaces (default: false)
vim.o.splitbelow = true -- force all horizontal splits to go below current window. (default: the new window opens above the current one)
vim.o.hlsearch = false -- set highlight on search (default: true)
vim.o.showmode = false -- we don't need to see things like -- INSERT -- anymore (default: true)
vim.o.termguicolors = true -- use 24-bit (true color) mode in the terminal instead of the older 256-color palette (default: false)
vim.o.numberwidth = 4 -- set the minimum width of the line number column (the gutter where :set number displays line numbers)
vim.o.smartindent = true -- make indenting smarter again (default: false)
vim.o.showtabline = 2 -- always show tablines (default: 1)
vim.o.backspace = 'indent,eol,start' -- allow backspace on (default: 'indent,eol,start')
vim.o.pumheight = 10 -- pop up menu height (default: 0)
vim.o.conceallevel = 0 -- so that '' is visible in markdown files (default: 1)
vim.o.signcolumn = 'yes' -- always reserve one column for signs, to prevent text shifting when signs show up
vim.o.fileencoding = 'utf-8' -- the encoding written to a file (default: 'utf-8')
vim.o.cmdheight = 1 -- more space in the Neovim command line for displaying messages (default: 1)
vim.o.breakindent = true -- when a long line wraps onto multiple screen lines, the wrapped part will keep the same indentation as the first line (default: false)
vim.o.updatetime = 250 -- decrease update time (default: 4000)
vim.o.timeoutlen = 300 -- set the maximum time Neovim waits for the next key in a mapped sequence
vim.o.backup = false -- create a backup file (default: false)
vim.o.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited (default: true)
vim.o.undofile = true -- save undo history (default: false)
vim.o.completeopt = 'menuone,noselect' -- control how the completion menu behaves when you trigger completion (insert mode, <C-n>, or plugin auto-completion)
vim.opt.shortmess:append 'c' -- don't give |ins-completion-menu| messages (default: does not include 'c')
vim.opt.iskeyword:append '-' -- hyphenated words recognized by searches (default: does not include '-')
vim.opt.formatoptions:remove { 'c', 'r', 'o' } -- don't insert the current comment leader automatically for auto-wrapping comments using 'textwidth', hitting <ENTER> in insert mode, or hitting 'o' or 'O' in normal mode. (default: 'croql')
vim.opt.runtimepath:remove '/usr/share/vim/vimfiles' -- separate Vim plugins from Neovim in case Vim still in use (default: includes this path if Vim is installed)
