return {
  'romus204/tree-sitter-manager.nvim',
  dependencies = {}, -- tree-sitter CLI must be installed system-wide
  config = function()
    require('tree-sitter-manager').setup {
      ensure_installed = {
        'awk',
        'bash',
        'c',
        'css',
        'csv',
        'diff',
        'dockerfile',
        'elixir',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gpg',
        'graphql',
        'heex',
        'html',
        'javascript',
        'jq',
        'json',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'mermaid',
        'nginx',
        'sql',
        'todotxt',
        'toml',
        'tsx',
        'typescript',
        'udev',
        'query',
        'vim',
        'vimdoc',
        'yaml',
        'ruby',
      },
      auto_install = true,
      highlight = true,
    }
  end,
}
